OBJFILES = src/bmp2text.o src/csvlib.o src/gamedata.o src/menu.o
all: $(EXE)

$(EXE):  $(OBJFILES)
	$(CC) $(LINK_CFLAGS) -o $(EXE) $(OBJFILES) $(APP_LDFLAGS)
	$(STRIP) --strip-all $(EXE)
	$(STACKMOD)
	
menu.o: src/menu.c
	$(CC) -c $(CFLAGS) $< -o src/$@
	
bmp2text.o: src/bmp2text.c
	$(CC) -c $(CFLAGS) $< -o src/$@

gamedata.o: src/gamedata.c
	$(CC) -c $(CFLAGS) $< -o src/$@

csvlib.o: src/csvlib.c
	$(CC) -c $(CFLAGS) $< -o src/$@
	
clean:
	rm -f src/*.o src/*.a $(EXE) core