# Names of the compiler and friends
CC = gcc
STRIP = strip

# SDL libraries and paths
APP_LIB = -lSDL
APP_INCLUDE =          

# Compiler flags
override CFLAGS += -Wall -Wno-unused-function -Wno-unused-variable -O3 $(APP_INCLUDE) -DUSE_SDL -DPOSIX -DDIR_SEP=$(DIR_SEP) -DGAMEDIR=$(GAMEDIR) -DCSV_FILE=$(CSV_FILE)
LINK_CFLAGS = -Wall
APP_LDFLAGS = $(APP_LIB)

# What our application is named
EXE = menu

all: $(EXE)

include Makefile.common