# Names of the compiler and friends
CC = gcc
STRIP = strip

# SDL libraries and paths
SDL_LIB = -lSDL
SDL_INCLUDE =

# Compiler flags
CFLAGS = -Wall -Wno-unused-function -O3 $(SDL_INCLUDE) -DPOSIX -DDIR_SEP=$(DIR_SEP) -DGAMEDIR=$(GAMEDIR) -DCSV_FILE=$(CSV_FILE) -DLOGGING=$(LOGGING)
SDL_LDFLAGS = $(SDL_LIB)

# What our application is named
EXE = menu

include Makefile.common